import { homedir, hostname, platform } from 'node:os';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const CONFIG_DIR = path.join(homedir(), '.agentsam');
const CONFIG_FILE = path.join(CONFIG_DIR, 'bridge.env');

export async function loadConfig() {
  try {
    const raw = await readFile(CONFIG_FILE, 'utf8');
    const out = {};
    for (const line of raw.split('\n')) {
      const t = line.trim();
      if (!t || t.startsWith('#')) continue;
      const i = t.indexOf('=');
      if (i < 0) continue;
      out[t.slice(0, i)] = t.slice(i + 1);
    }
    return out;
  } catch {
    return {};
  }
}

export async function saveConfig(entries) {
  await mkdir(CONFIG_DIR, { recursive: true });
  const lines = [
    '# Agent Sam bridge — generated by agentsam-bridge pair',
    ...Object.entries(entries).map(([k, v]) => `${k}=${v}`),
  ];
  await writeFile(CONFIG_FILE, `${lines.join('\n')}\n`, { mode: 0o600 });
  return CONFIG_FILE;
}

export function defaultDeviceName() {
  return hostname().split('.')[0] || 'my-machine';
}

export function defaultPlatform() {
  const p = platform();
  if (p === 'darwin') return 'macos';
  if (p === 'win32') return 'windows';
  return 'linux';
}

export function normalizeCode(code) {
  return String(code || '').replace(/[^A-Za-z0-9]/g, '').toUpperCase();
}

export function formatCode(code) {
  const c = normalizeCode(code);
  if (c.length <= 4) return c;
  return `${c.slice(0, 4)}-${c.slice(4, 8)}`;
}
